export enum DownloadState {
    IDLE = "IDLE",
    CHECKING_UPDATES = "CHECKING_UPDATES",
    CHECKING_FILES = "CHECKING_FILES",
    READY_FOR_DOWNLOAD = "READY_FOR_DOWNLOAD",
    DOWNLOADING = "DOWNLOADING",
    PAUSED = "PAUSED",
    DONE = "DONE"
}